### PR TITLE
Optionally compress binaries with UPX

### PR DESCRIPTION
**Pull request by lwbt**
I added a function to compress the binaries with UPX. A few other modifications come from my experience with shellcheck and pre-commit. Please review.

I'm extracting and compressing the binaries one at a time to be considerate about environments where storage space is scarce.

I also created an asciinema recording and a pre-commit configuration which are not part of this PR.

### CODE REVIEW

**Comment by admonstrator** [comment]
Do you have any information about how much space is saved by UPX?

**Comment by lwbt** [comment]
The tailscale binary compresses down to ~45% of it's original size when using LZMA.

```
16082278 ->   7182820   44.66%    linux/arm    tailscale
```

Without LZMA it's still about 53%.

```
16082278 ->   8456884   52.59%    linux/arm    tailscale
```

On my router the uncompressed binaries consume 33.8 MB, leaving 19.4 MB available in overlayfs. The compressed binaries consume 21.7 MB, leaving 31.5 MB available. My router had 50.6 MB of free space available in overlayfs before replacing the binaries. I would say these are significant space savings under these circumstances. I'm not a fan of modifying binaries myself, it's more of a last resort.

I made a few more notes here: https://github.com/lwbt/glinet.forum/blob/main/scripts/update-tailscale/notes.adoc

The ideal option to save space would be to flash an image with updated binaries of Tailscale to avoid consuming space in the overlayfs. (I used to build my own customized OpenWrt images to some extend a few years ago when my life was less busy.) But it looks like they release a new binary every few weeks.

When I have time I would like to create code to check if there is a new release available, if it is a security fix, and to allow for unattended updates, so that users could run it as a cron job.

**Comment by admonstrator** [comment]
Looks pretty good so far, I will definitely integrate into the script. I am currently thinking about kicking the backup function as well because the original file should be available within `/rom` anyway.

**Comment by admonstrator** [comment]
Maybe you want to take a look into this new version?
https://github.com/Admonstrator/glinet.forum/tree/tailscale-upx/scripts/update-tailscale

**Comment by lwbt** [comment]
Looks good. :+1: 

I'm not sure if I should create new issues, but here are my findings and notes after testing:

- https://github.com/Admonstrator/glinet.forum/blob/398b51b41b48ba0925df9afdea9d98681cb0350c/scripts/update-tailscale/update-tailscale.sh#L98
  This gives me `tar: removing leading '/' from member names`. It still works, but should be replaced with:
  ```bash
  tar czf "/root/tailscale_config_backup_$TIMESTAMP.tar.gz" -C "/" "etc/config/tailscale"
  ```
  I found it in this thread: https://unix.stackexchange.com/questions/59243/tar-removing-leading-from-member-names
- Since you removed a feature, adding the version number to the top right of the banner should be considered. :slightly_smiling_face: 
- I created a new recording: [asciinema.org/a/WHdcANiAyGvtlzE26weqbNQ9c](https://asciinema.org/a/WHdcANiAyGvtlzE26weqbNQ9c)
  - `yes` is part of BusyBox, so an unattended installation can be performed with `yes | ./update-tailscale.sh` as I have done in the recording
  -  Why do I create these? 1.) It serves as documentation for me. What did this script in this version again? 2.) Users feel intimidated when they don’t know what to expect will happen. Stopping playback of a demonstration any time and being able to go back a few steps should make it easier. 
  - It’s all text, you can edit and re-upload it with ease.
  - The banner at the start looks quite busy on 80×24 standard size. I could use any other size for recording, but I would suggest to consider adding a slight delay, presenting some content in a more compact form (prerequisites and preflight check are a bit redundant) or removing non-essential content. While I appreciate being mentioned in the script code and the readme, I’m completely fine with not being mentioned at the start of the script for the sake of better UX. :slightly_smiling_face: 
- Config backups:
  - If used regularly or as cronjob, `/root/tailscale_config_backup_${timestamp}.tar.gz` in `/etc/sysupgrade.conf` should be limited to a reasonable amount of entries.
  - I would suggest creating a subfolder for the backup and adding that folder to `/etc/sysupgrade.conf` like it is done for `/etc/config/gl_nas/`, at least in my configuration.
- Prompts for user input could be styled a bit to make it more clear and compact. It’s not GNU read with readline or charmbracelet/gum, but something like the following might look nicer: `echo -e -n "> \033[36mAre you sure you want to continue?\033[0m (y/N) " && read -r` It would require a bit of refactoring in some places as I have noticed. Not sure if it’s worth the effort.

**Comment by lwbt** [comment]
https://github.com/Admonstrator/glinet.forum/blob/398b51b41b48ba0925df9afdea9d98681cb0350c/scripts/update-tailscale/update-tailscale.sh#L295

Have you checked that this restore procedure works **and** also frees up space in overlayfs? If found the following thread: https://stackoverflow.com/questions/57865670/overlayfs-restore-removed-or-changed-file-from-lower

Deleting the file an remounting `/` should restore the old binaries. Instead of remount, which might just work or cause issues with other processes, the router could just be rebooted after deleting the newer binaries.

**Comment by admonstrator** [comment]
>yes is part of BusyBox, so an unattended installation can be performed with yes | ./update-tailscale.sh as I have done in the recording

I agree that this would be a way to go, but since most GL users are not experienced, I would like to stick to the command lines instead. They are more windows-style, which is great for people without any experience. And it doesn't hurt anyway.

>The banner at the start looks quite busy on 80×24 standard size

True. But there is no default size for people using GL routers. I saw people using Windows Terminal (which is larger) or even some apps on their mobile phones to connect by SSH. Not many of them using OS X or Linux with a default terminal size. Maybe I will add some option to skip headers to get a more straightforward output.

>If used regularly or as cronjob, /root/tailscale_config_backup_${timestamp}.tar.gz in /etc/sysupgrade.conf should be limited to a reasonable amount of entries.

Only the latest backup will now be kept in `/etc/sysupgrade.conf`

>Have you checked that this restore procedure works and also frees up space in overlayfs? 

Well, yes and no. Spoken of restoring the binaries: It works and occupies **more** space because the GL version isn't UPX packed...
Spoken of using these binaries with some previous tailscale config: No, does not work.

**Comment by admonstrator** [comment]
Thanks for your help, I really appreciate it! @lwbt 
The feature was merged into main and testing - at least at my end - was successfully! #7

**Pull request merged**
